services:
  postgres:
    image: postgres:18.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: siakad
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  backend:
    build: ./backend-api 
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: siakad
      JWT_SECRET: go-siakad-secret
    depends_on:
      - postgres

volumes:
  pgdata: